// Code generated by "enumer -type=ErrorCode -transform=snake-upper -trimprefix=ErrorCode"; DO NOT EDIT.

package skydio

import (
	"fmt"
	"strings"
)

const _ErrorCodeName = "SUCCESSRATE_LIMIT_EXCEEDED_ERRORPERMISSIONS_ERRORFEATURE_NOT_ENABLED_ERRORINVALID_TOKENNOT_FOUNDVEHICLE_NOT_FOUNDDOCK_NOT_FOUNDALERT_CONFIG_NOT_FOUNDWEBHOOK_NOT_FOUNDFLIGHT_NOT_FOUNDBATTERY_NOT_FOUNDATTACHMENT_NOT_FOUNDMARKER_NOT_FOUNDUSER_NOT_FOUNDSCAN_NOT_FOUNDAPI_TOKEN_NOT_FOUNDFLIGHT_DATA_FILE_NOT_FOUNDMISSION_TEMPLATE_NOT_FOUNDBAD_REQUESTBAD_ARGSSCHEMA_VALIDATION_ERRORINTEGRITY_ERROROVERWRITE_PROTECTEDDEVICE_OFFLINEEXTERNAL_TELEMETRY_ERRORSTRUCTURE_NOT_FOUNDCLOUD_IN_MAINTENANCE"
const _ErrorCodeLowerName = "successrate_limit_exceeded_errorpermissions_errorfeature_not_enabled_errorinvalid_tokennot_foundvehicle_not_founddock_not_foundalert_config_not_foundwebhook_not_foundflight_not_foundbattery_not_foundattachment_not_foundmarker_not_founduser_not_foundscan_not_foundapi_token_not_foundflight_data_file_not_foundmission_template_not_foundbad_requestbad_argsschema_validation_errorintegrity_erroroverwrite_protecteddevice_offlineexternal_telemetry_errorstructure_not_foundcloud_in_maintenance"

var _ErrorCodeMap = map[ErrorCode]string{
	0:    _ErrorCodeName[0:7],
	1429: _ErrorCodeName[7:32],
	2000: _ErrorCodeName[32:49],
	2005: _ErrorCodeName[49:74],
	3300: _ErrorCodeName[74:87],
	4100: _ErrorCodeName[87:96],
	4200: _ErrorCodeName[96:113],
	4250: _ErrorCodeName[113:127],
	4345: _ErrorCodeName[127:149],
	4360: _ErrorCodeName[149:166],
	4400: _ErrorCodeName[166:182],
	4450: _ErrorCodeName[182:199],
	4480: _ErrorCodeName[199:219],
	4490: _ErrorCodeName[219:235],
	4500: _ErrorCodeName[235:249],
	4551: _ErrorCodeName[249:263],
	4575: _ErrorCodeName[263:282],
	4700: _ErrorCodeName[282:308],
	4996: _ErrorCodeName[308:334],
	5000: _ErrorCodeName[334:345],
	5100: _ErrorCodeName[345:353],
	5110: _ErrorCodeName[353:376],
	7000: _ErrorCodeName[376:391],
	7100: _ErrorCodeName[391:410],
	7800: _ErrorCodeName[410:424],
	8000: _ErrorCodeName[424:448],
	8200: _ErrorCodeName[448:467],
	8300: _ErrorCodeName[467:487],
}

func (i ErrorCode) String() string {
	if str, ok := _ErrorCodeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ErrorCode(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ErrorCodeNoOp() {
	var x [1]struct{}
	_ = x[ErrorCodeSuccess-(0)]
	_ = x[ErrorCodeRateLimitExceededError-(1429)]
	_ = x[ErrorCodePermissionsError-(2000)]
	_ = x[ErrorCodeFeatureNotEnabledError-(2005)]
	_ = x[ErrorCodeInvalidToken-(3300)]
	_ = x[ErrorCodeNotFound-(4100)]
	_ = x[ErrorCodeVehicleNotFound-(4200)]
	_ = x[ErrorCodeDockNotFound-(4250)]
	_ = x[ErrorCodeAlertConfigNotFound-(4345)]
	_ = x[ErrorCodeWebhookNotFound-(4360)]
	_ = x[ErrorCodeFlightNotFound-(4400)]
	_ = x[ErrorCodeBatteryNotFound-(4450)]
	_ = x[ErrorCodeAttachmentNotFound-(4480)]
	_ = x[ErrorCodeMarkerNotFound-(4490)]
	_ = x[ErrorCodeUserNotFound-(4500)]
	_ = x[ErrorCodeScanNotFound-(4551)]
	_ = x[ErrorCodeApiTokenNotFound-(4575)]
	_ = x[ErrorCodeFlightDataFileNotFound-(4700)]
	_ = x[ErrorCodeMissionTemplateNotFound-(4996)]
	_ = x[ErrorCodeBadRequest-(5000)]
	_ = x[ErrorCodeBadArgs-(5100)]
	_ = x[ErrorCodeSchemaValidationError-(5110)]
	_ = x[ErrorCodeIntegrityError-(7000)]
	_ = x[ErrorCodeOverwriteProtected-(7100)]
	_ = x[ErrorCodeDeviceOffline-(7800)]
	_ = x[ErrorCodeExternalTelemetryError-(8000)]
	_ = x[ErrorCodeStructureNotFound-(8200)]
	_ = x[ErrorCodeCloudInMaintenance-(8300)]
}

var _ErrorCodeValues = []ErrorCode{ErrorCodeSuccess, ErrorCodeRateLimitExceededError, ErrorCodePermissionsError, ErrorCodeFeatureNotEnabledError, ErrorCodeInvalidToken, ErrorCodeNotFound, ErrorCodeVehicleNotFound, ErrorCodeDockNotFound, ErrorCodeAlertConfigNotFound, ErrorCodeWebhookNotFound, ErrorCodeFlightNotFound, ErrorCodeBatteryNotFound, ErrorCodeAttachmentNotFound, ErrorCodeMarkerNotFound, ErrorCodeUserNotFound, ErrorCodeScanNotFound, ErrorCodeApiTokenNotFound, ErrorCodeFlightDataFileNotFound, ErrorCodeMissionTemplateNotFound, ErrorCodeBadRequest, ErrorCodeBadArgs, ErrorCodeSchemaValidationError, ErrorCodeIntegrityError, ErrorCodeOverwriteProtected, ErrorCodeDeviceOffline, ErrorCodeExternalTelemetryError, ErrorCodeStructureNotFound, ErrorCodeCloudInMaintenance}

var _ErrorCodeNameToValueMap = map[string]ErrorCode{
	_ErrorCodeName[0:7]:          ErrorCodeSuccess,
	_ErrorCodeLowerName[0:7]:     ErrorCodeSuccess,
	_ErrorCodeName[7:32]:         ErrorCodeRateLimitExceededError,
	_ErrorCodeLowerName[7:32]:    ErrorCodeRateLimitExceededError,
	_ErrorCodeName[32:49]:        ErrorCodePermissionsError,
	_ErrorCodeLowerName[32:49]:   ErrorCodePermissionsError,
	_ErrorCodeName[49:74]:        ErrorCodeFeatureNotEnabledError,
	_ErrorCodeLowerName[49:74]:   ErrorCodeFeatureNotEnabledError,
	_ErrorCodeName[74:87]:        ErrorCodeInvalidToken,
	_ErrorCodeLowerName[74:87]:   ErrorCodeInvalidToken,
	_ErrorCodeName[87:96]:        ErrorCodeNotFound,
	_ErrorCodeLowerName[87:96]:   ErrorCodeNotFound,
	_ErrorCodeName[96:113]:       ErrorCodeVehicleNotFound,
	_ErrorCodeLowerName[96:113]:  ErrorCodeVehicleNotFound,
	_ErrorCodeName[113:127]:      ErrorCodeDockNotFound,
	_ErrorCodeLowerName[113:127]: ErrorCodeDockNotFound,
	_ErrorCodeName[127:149]:      ErrorCodeAlertConfigNotFound,
	_ErrorCodeLowerName[127:149]: ErrorCodeAlertConfigNotFound,
	_ErrorCodeName[149:166]:      ErrorCodeWebhookNotFound,
	_ErrorCodeLowerName[149:166]: ErrorCodeWebhookNotFound,
	_ErrorCodeName[166:182]:      ErrorCodeFlightNotFound,
	_ErrorCodeLowerName[166:182]: ErrorCodeFlightNotFound,
	_ErrorCodeName[182:199]:      ErrorCodeBatteryNotFound,
	_ErrorCodeLowerName[182:199]: ErrorCodeBatteryNotFound,
	_ErrorCodeName[199:219]:      ErrorCodeAttachmentNotFound,
	_ErrorCodeLowerName[199:219]: ErrorCodeAttachmentNotFound,
	_ErrorCodeName[219:235]:      ErrorCodeMarkerNotFound,
	_ErrorCodeLowerName[219:235]: ErrorCodeMarkerNotFound,
	_ErrorCodeName[235:249]:      ErrorCodeUserNotFound,
	_ErrorCodeLowerName[235:249]: ErrorCodeUserNotFound,
	_ErrorCodeName[249:263]:      ErrorCodeScanNotFound,
	_ErrorCodeLowerName[249:263]: ErrorCodeScanNotFound,
	_ErrorCodeName[263:282]:      ErrorCodeApiTokenNotFound,
	_ErrorCodeLowerName[263:282]: ErrorCodeApiTokenNotFound,
	_ErrorCodeName[282:308]:      ErrorCodeFlightDataFileNotFound,
	_ErrorCodeLowerName[282:308]: ErrorCodeFlightDataFileNotFound,
	_ErrorCodeName[308:334]:      ErrorCodeMissionTemplateNotFound,
	_ErrorCodeLowerName[308:334]: ErrorCodeMissionTemplateNotFound,
	_ErrorCodeName[334:345]:      ErrorCodeBadRequest,
	_ErrorCodeLowerName[334:345]: ErrorCodeBadRequest,
	_ErrorCodeName[345:353]:      ErrorCodeBadArgs,
	_ErrorCodeLowerName[345:353]: ErrorCodeBadArgs,
	_ErrorCodeName[353:376]:      ErrorCodeSchemaValidationError,
	_ErrorCodeLowerName[353:376]: ErrorCodeSchemaValidationError,
	_ErrorCodeName[376:391]:      ErrorCodeIntegrityError,
	_ErrorCodeLowerName[376:391]: ErrorCodeIntegrityError,
	_ErrorCodeName[391:410]:      ErrorCodeOverwriteProtected,
	_ErrorCodeLowerName[391:410]: ErrorCodeOverwriteProtected,
	_ErrorCodeName[410:424]:      ErrorCodeDeviceOffline,
	_ErrorCodeLowerName[410:424]: ErrorCodeDeviceOffline,
	_ErrorCodeName[424:448]:      ErrorCodeExternalTelemetryError,
	_ErrorCodeLowerName[424:448]: ErrorCodeExternalTelemetryError,
	_ErrorCodeName[448:467]:      ErrorCodeStructureNotFound,
	_ErrorCodeLowerName[448:467]: ErrorCodeStructureNotFound,
	_ErrorCodeName[467:487]:      ErrorCodeCloudInMaintenance,
	_ErrorCodeLowerName[467:487]: ErrorCodeCloudInMaintenance,
}

var _ErrorCodeNames = []string{
	_ErrorCodeName[0:7],
	_ErrorCodeName[7:32],
	_ErrorCodeName[32:49],
	_ErrorCodeName[49:74],
	_ErrorCodeName[74:87],
	_ErrorCodeName[87:96],
	_ErrorCodeName[96:113],
	_ErrorCodeName[113:127],
	_ErrorCodeName[127:149],
	_ErrorCodeName[149:166],
	_ErrorCodeName[166:182],
	_ErrorCodeName[182:199],
	_ErrorCodeName[199:219],
	_ErrorCodeName[219:235],
	_ErrorCodeName[235:249],
	_ErrorCodeName[249:263],
	_ErrorCodeName[263:282],
	_ErrorCodeName[282:308],
	_ErrorCodeName[308:334],
	_ErrorCodeName[334:345],
	_ErrorCodeName[345:353],
	_ErrorCodeName[353:376],
	_ErrorCodeName[376:391],
	_ErrorCodeName[391:410],
	_ErrorCodeName[410:424],
	_ErrorCodeName[424:448],
	_ErrorCodeName[448:467],
	_ErrorCodeName[467:487],
}

// ErrorCodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ErrorCodeString(s string) (ErrorCode, error) {
	if val, ok := _ErrorCodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ErrorCodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ErrorCode values", s)
}

// ErrorCodeValues returns all values of the enum
func ErrorCodeValues() []ErrorCode {
	return _ErrorCodeValues
}

// ErrorCodeStrings returns a slice of all String values of the enum
func ErrorCodeStrings() []string {
	strs := make([]string, len(_ErrorCodeNames))
	copy(strs, _ErrorCodeNames)
	return strs
}

// IsAErrorCode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ErrorCode) IsAErrorCode() bool {
	_, ok := _ErrorCodeMap[i]
	return ok
}
