// Code generated by "enumer -type=MissionCompletedReturnType -transform=snake-upper -trimprefix=MissionCompletedReturnType"; DO NOT EDIT.

package skydio

import (
	"fmt"
	"strings"
)

const _MissionCompletedReturnTypeName = "DEFAULT"

var _MissionCompletedReturnTypeIndex = [...]uint8{0, 7}

const _MissionCompletedReturnTypeLowerName = "default"

func (i MissionCompletedReturnType) String() string {
	if i >= MissionCompletedReturnType(len(_MissionCompletedReturnTypeIndex)-1) {
		return fmt.Sprintf("MissionCompletedReturnType(%d)", i)
	}
	return _MissionCompletedReturnTypeName[_MissionCompletedReturnTypeIndex[i]:_MissionCompletedReturnTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MissionCompletedReturnTypeNoOp() {
	var x [1]struct{}
	_ = x[MissionCompletedReturnTypeDefault-(0)]
}

var _MissionCompletedReturnTypeValues = []MissionCompletedReturnType{MissionCompletedReturnTypeDefault}

var _MissionCompletedReturnTypeNameToValueMap = map[string]MissionCompletedReturnType{
	_MissionCompletedReturnTypeName[0:7]:      MissionCompletedReturnTypeDefault,
	_MissionCompletedReturnTypeLowerName[0:7]: MissionCompletedReturnTypeDefault,
}

var _MissionCompletedReturnTypeNames = []string{
	_MissionCompletedReturnTypeName[0:7],
}

// MissionCompletedReturnTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MissionCompletedReturnTypeString(s string) (MissionCompletedReturnType, error) {
	if val, ok := _MissionCompletedReturnTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MissionCompletedReturnTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MissionCompletedReturnType values", s)
}

// MissionCompletedReturnTypeValues returns all values of the enum
func MissionCompletedReturnTypeValues() []MissionCompletedReturnType {
	return _MissionCompletedReturnTypeValues
}

// MissionCompletedReturnTypeStrings returns a slice of all String values of the enum
func MissionCompletedReturnTypeStrings() []string {
	strs := make([]string, len(_MissionCompletedReturnTypeNames))
	copy(strs, _MissionCompletedReturnTypeNames)
	return strs
}

// IsAMissionCompletedReturnType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MissionCompletedReturnType) IsAMissionCompletedReturnType() bool {
	for _, v := range _MissionCompletedReturnTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
